//! X.509 chain validation for the browser's TLS 1.3 client.
//!
//! What is *not* hand-written here: path building, validity dates, host name
//! matching, `basicConstraints` / `keyUsage` / extended key usage, name
//! constraints and path-length checks all come from the reviewed
//! `rustls-webpki` crate, and the signature maths from the pure-Rust RustCrypto
//! crates (`p256`, `p384`, `rsa`, `sha2`). This module supplies:
//!
//! * the signature algorithm table webpki asks for (RSA PKCS#1 v1.5 and PSS
//!   with SHA-256/384/512, ECDSA P-256 and P-384 with SHA-256/384; RSA keys must
//!   be 2048-8192 bits);
//! * the embedded **trust store** ([`TrustStore`], data in
//!   `osjeff_core/data/trust-store.bin`, regenerated by
//!   `tools/gen-trust-store.sh`, every root listed with its SHA-256 in
//!   `trust-store.sha256`);
//! * hard limits (chain length, certificate size) and an error type
//!   ([`CertError`]) that says in plain words why a chain was refused;
//! * the TLS 1.3 `CertificateVerify` check ([`verify_handshake_signature`]).
//!
//! There is no revocation checking (no CRL, no OCSP, no stapling) and no
//! pinning; see `docs/SECURITY-MODEL.md`.

use crate::x509;
use alloc::vec::Vec;
use core::time::Duration;
use p256::ecdsa::signature::hazmat::PrehashVerifier;
use rsa::pkcs1::DecodeRsaPublicKey;
use rsa::traits::PublicKeyParts;
use rustls_pki_types::{
    AlgorithmIdentifier, CertificateDer, InvalidSignature, ServerName,
    SignatureVerificationAlgorithm, UnixTime, alg_id,
};
use sha2::{Digest, Sha256, Sha384, Sha512};

/// Longest handshake the verifier tolerates in total, for the caller's
/// deadline (the TLS layer enforces it; kept here so the policy is in one
/// place and documented).
pub const MAX_HANDSHAKE_MS: u64 = 30_000;
/// Smallest and largest RSA modulus accepted (bits).
pub const RSA_MIN_BITS: usize = 2048;
pub const RSA_MAX_BITS: usize = 8192;

// ---- errors ----

/// Why a server certificate chain was refused.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CertError {
    /// A certificate could not be parsed.
    BadEncoding,
    /// A certificate or the whole chain exceeds the size limits.
    TooLarge,
    /// More certificates than [`x509::MAX_CHAIN_LEN`], or a path too deep.
    ChainTooLong,
    /// `notAfter` is in the past.
    Expired,
    /// `notBefore` is in the future.
    NotYetValid,
    /// The certificate is not valid for the host name asked for.
    NameMismatch,
    /// The server's own certificate signed itself.
    SelfSigned,
    /// No path to a trusted root (unknown root or missing intermediate).
    UnknownIssuer,
    /// A signature does not verify.
    BadSignature,
    /// A certificate is used as a CA without being one (or the reverse).
    NotCa,
    /// Name constraints, path-length or key-usage constraints violated.
    Constraint,
    /// Signature algorithm or key size not supported.
    Unsupported,
    /// The system clock is not a plausible date, so validity cannot be judged.
    ClockUnset,
    /// Anything else webpki reports.
    Other,
}

impl CertError {
    /// Short reason for the serial log (English, ASCII). The person sees `web.err.cert.*`.
    pub fn reason(self) -> &'static str {
        match self {
            CertError::BadEncoding => "malformed certificate",
            CertError::TooLarge => "certificate too large",
            CertError::ChainTooLong => "chain too long",
            CertError::Expired => "expired",
            CertError::NotYetValid => "not yet valid",
            CertError::NameMismatch => "name mismatch",
            CertError::SelfSigned => "self-signed, untrusted chain",
            CertError::UnknownIssuer => "untrusted chain",
            CertError::BadSignature => "bad signature",
            CertError::NotCa => "invalid CA in chain",
            CertError::Constraint => "chain constraint violated",
            CertError::Unsupported => "unsupported algorithm",
            CertError::ClockUnset => "system clock wrong",
            CertError::Other => "chain rejected",
        }
    }

    /// True when a wrong system clock is a plausible cause: the UI adds the
    /// "hora do sistema incorreta / nao confirmada" hint.
    pub fn clock_may_be_to_blame(self) -> bool {
        matches!(
            self,
            CertError::Expired | CertError::NotYetValid | CertError::ClockUnset
        )
    }
}

// ---- signature algorithms ----

#[derive(Clone, Copy, Debug)]
enum Hash {
    S256,
    S384,
    S512,
}

impl Hash {
    fn digest(self, msg: &[u8]) -> Vec<u8> {
        match self {
            Hash::S256 => Sha256::digest(msg).to_vec(),
            Hash::S384 => Sha384::digest(msg).to_vec(),
            Hash::S512 => Sha512::digest(msg).to_vec(),
        }
    }
}

#[derive(Debug)]
struct Ecdsa {
    p384: bool,
    hash: Hash,
    pk_alg: AlgorithmIdentifier,
    sig_alg: AlgorithmIdentifier,
}

impl SignatureVerificationAlgorithm for Ecdsa {
    fn verify_signature(
        &self,
        public_key: &[u8],
        message: &[u8],
        signature: &[u8],
    ) -> Result<(), InvalidSignature> {
        let digest = self.hash.digest(message);
        if self.p384 {
            let key = p384::ecdsa::VerifyingKey::from_sec1_bytes(public_key)
                .map_err(|_| InvalidSignature)?;
            let sig = p384::ecdsa::Signature::from_der(signature).map_err(|_| InvalidSignature)?;
            key.verify_prehash(&digest, &sig)
                .map_err(|_| InvalidSignature)
        } else {
            let key = p256::ecdsa::VerifyingKey::from_sec1_bytes(public_key)
                .map_err(|_| InvalidSignature)?;
            let sig = p256::ecdsa::Signature::from_der(signature).map_err(|_| InvalidSignature)?;
            key.verify_prehash(&digest, &sig)
                .map_err(|_| InvalidSignature)
        }
    }
    fn public_key_alg_id(&self) -> AlgorithmIdentifier {
        self.pk_alg
    }
    fn signature_alg_id(&self) -> AlgorithmIdentifier {
        self.sig_alg
    }
}

#[derive(Debug)]
struct RsaAlg {
    pss: bool,
    hash: Hash,
    sig_alg: AlgorithmIdentifier,
}

fn rsa_key(public_key: &[u8]) -> Result<rsa::RsaPublicKey, InvalidSignature> {
    let key = rsa::RsaPublicKey::from_pkcs1_der(public_key).map_err(|_| InvalidSignature)?;
    let bits = key.size() * 8;
    if !(RSA_MIN_BITS..=RSA_MAX_BITS).contains(&bits) {
        return Err(InvalidSignature);
    }
    Ok(key)
}

impl SignatureVerificationAlgorithm for RsaAlg {
    fn verify_signature(
        &self,
        public_key: &[u8],
        message: &[u8],
        signature: &[u8],
    ) -> Result<(), InvalidSignature> {
        use rsa::signature::Verifier;
        let key = rsa_key(public_key)?;
        // The signature must be exactly the modulus length.
        if signature.len() != key.size() {
            return Err(InvalidSignature);
        }
        macro_rules! check {
            ($h:ty) => {{
                if self.pss {
                    let sig =
                        rsa::pss::Signature::try_from(signature).map_err(|_| InvalidSignature)?;
                    rsa::pss::VerifyingKey::<$h>::new(key)
                        .verify(message, &sig)
                        .map_err(|_| InvalidSignature)
                } else {
                    let sig = rsa::pkcs1v15::Signature::try_from(signature)
                        .map_err(|_| InvalidSignature)?;
                    rsa::pkcs1v15::VerifyingKey::<$h>::new(key)
                        .verify(message, &sig)
                        .map_err(|_| InvalidSignature)
                }
            }};
        }
        match self.hash {
            Hash::S256 => check!(Sha256),
            Hash::S384 => check!(Sha384),
            Hash::S512 => check!(Sha512),
        }
    }
    fn public_key_alg_id(&self) -> AlgorithmIdentifier {
        alg_id::RSA_ENCRYPTION
    }
    fn signature_alg_id(&self) -> AlgorithmIdentifier {
        self.sig_alg
    }
}

static ECDSA_P256_SHA256: Ecdsa = Ecdsa {
    p384: false,
    hash: Hash::S256,
    pk_alg: alg_id::ECDSA_P256,
    sig_alg: alg_id::ECDSA_SHA256,
};
static ECDSA_P256_SHA384: Ecdsa = Ecdsa {
    p384: false,
    hash: Hash::S384,
    pk_alg: alg_id::ECDSA_P256,
    sig_alg: alg_id::ECDSA_SHA384,
};
static ECDSA_P384_SHA256: Ecdsa = Ecdsa {
    p384: true,
    hash: Hash::S256,
    pk_alg: alg_id::ECDSA_P384,
    sig_alg: alg_id::ECDSA_SHA256,
};
static ECDSA_P384_SHA384: Ecdsa = Ecdsa {
    p384: true,
    hash: Hash::S384,
    pk_alg: alg_id::ECDSA_P384,
    sig_alg: alg_id::ECDSA_SHA384,
};
static RSA_PKCS1_SHA256: RsaAlg = RsaAlg {
    pss: false,
    hash: Hash::S256,
    sig_alg: alg_id::RSA_PKCS1_SHA256,
};
static RSA_PKCS1_SHA384: RsaAlg = RsaAlg {
    pss: false,
    hash: Hash::S384,
    sig_alg: alg_id::RSA_PKCS1_SHA384,
};
static RSA_PKCS1_SHA512: RsaAlg = RsaAlg {
    pss: false,
    hash: Hash::S512,
    sig_alg: alg_id::RSA_PKCS1_SHA512,
};
static RSA_PSS_SHA256: RsaAlg = RsaAlg {
    pss: true,
    hash: Hash::S256,
    sig_alg: alg_id::RSA_PSS_SHA256,
};
static RSA_PSS_SHA384: RsaAlg = RsaAlg {
    pss: true,
    hash: Hash::S384,
    sig_alg: alg_id::RSA_PSS_SHA384,
};
static RSA_PSS_SHA512: RsaAlg = RsaAlg {
    pss: true,
    hash: Hash::S512,
    sig_alg: alg_id::RSA_PSS_SHA512,
};

/// Algorithms allowed for signatures inside certificates.
static CHAIN_ALGS: [&dyn SignatureVerificationAlgorithm; 10] = [
    &ECDSA_P256_SHA256,
    &ECDSA_P256_SHA384,
    &ECDSA_P384_SHA256,
    &ECDSA_P384_SHA384,
    &RSA_PKCS1_SHA256,
    &RSA_PKCS1_SHA384,
    &RSA_PKCS1_SHA512,
    &RSA_PSS_SHA256,
    &RSA_PSS_SHA384,
    &RSA_PSS_SHA512,
];

/// TLS 1.3 `SignatureScheme` code points usable in `CertificateVerify`
/// (RFC 8446 4.2.3: PKCS#1 v1.5 is forbidden there, only PSS and ECDSA).
fn handshake_alg(scheme: u16) -> Option<&'static dyn SignatureVerificationAlgorithm> {
    match scheme {
        0x0403 => Some(&ECDSA_P256_SHA256),
        0x0503 => Some(&ECDSA_P384_SHA384),
        0x0804 => Some(&RSA_PSS_SHA256),
        0x0805 => Some(&RSA_PSS_SHA384),
        0x0806 => Some(&RSA_PSS_SHA512),
        _ => None,
    }
}

// ---- trust store ----

const STORE_BLOB: &[u8] = include_bytes!("../data/trust-store.bin");
const STORE_MANIFEST: &str = include_str!("../data/trust-store.sha256");
const STORE_MAGIC: &[u8; 6] = b"OJTS1\0";

/// The embedded root certificates.
pub struct TrustStore {
    certs: Vec<&'static [u8]>,
}

impl TrustStore {
    /// The store compiled into this build.
    pub fn embedded() -> TrustStore {
        TrustStore::parse(STORE_BLOB).unwrap_or(TrustStore { certs: Vec::new() })
    }

    /// Parse the blob format: magic, big-endian `u16` count, then per root a
    /// big-endian `u16` length and the DER bytes.
    pub fn parse(blob: &'static [u8]) -> Option<TrustStore> {
        let rest = blob.strip_prefix(STORE_MAGIC.as_slice())?;
        let (count, mut rest) = rest.split_first_chunk::<2>()?;
        let count = usize::from(u16::from_be_bytes(*count));
        let mut certs = Vec::with_capacity(count.min(1024));
        for _ in 0..count {
            let (len, r) = rest.split_first_chunk::<2>()?;
            let len = usize::from(u16::from_be_bytes(*len));
            if len > x509::MAX_CERT_LEN || r.len() < len {
                return None;
            }
            let (der, r) = r.split_at(len);
            certs.push(der);
            rest = r;
        }
        rest.is_empty().then_some(TrustStore { certs })
    }

    /// A store holding exactly these roots (tests, fuzzing and tools; the
    /// browser always uses [`TrustStore::embedded`]).
    pub fn from_certs(certs: Vec<&'static [u8]>) -> TrustStore {
        TrustStore { certs }
    }

    pub fn len(&self) -> usize {
        self.certs.len()
    }

    pub fn is_empty(&self) -> bool {
        self.certs.is_empty()
    }

    pub fn der(&self, i: usize) -> Option<&'static [u8]> {
        self.certs.get(i).copied()
    }

    /// SHA-256 of root `i` (what `trust-store.sha256` documents).
    pub fn fingerprint(&self, i: usize) -> Option<[u8; 32]> {
        self.certs.get(i).map(|d| Sha256::digest(d).into())
    }

    /// The manifest line for root `i`: `(sha256 hex, name)`.
    pub fn manifest_entry(i: usize) -> Option<(&'static str, &'static str)> {
        STORE_MANIFEST
            .lines()
            .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
            .nth(i)
            .and_then(|l| l.split_once("  "))
    }

    fn anchors(&self) -> Vec<rustls_pki_types::TrustAnchor<'static>> {
        self.certs
            .iter()
            .filter_map(|d| {
                webpki::anchor_from_trusted_cert(&CertificateDer::from_slice(d))
                    .ok()
                    .map(|a| a.to_owned())
            })
            .collect()
    }
}

// ---- the chain check ----

/// Result of a successful chain validation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Verified {
    /// Number of certificates the server sent.
    pub chain_len: usize,
    /// Index of the root in the embedded store (for the log), if found.
    pub root: Option<usize>,
}

fn map_error(e: webpki::Error, leaf: &[u8]) -> CertError {
    use webpki::Error as E;
    let self_issued = x509::parse(leaf).is_ok_and(|c| c.is_self_issued());
    match e {
        E::CertExpired { .. } => CertError::Expired,
        E::CertNotValidYet { .. } => CertError::NotYetValid,
        E::CertNotValidForName(_) => CertError::NameMismatch,
        E::UnknownIssuer | E::CaUsedAsEndEntity if self_issued => CertError::SelfSigned,
        E::UnknownIssuer => CertError::UnknownIssuer,
        E::InvalidSignatureForPublicKey => CertError::BadSignature,
        E::CaUsedAsEndEntity | E::EndEntityUsedAsCa => CertError::NotCa,
        E::PathLenConstraintViolated
        | E::NameConstraintViolation
        | E::RequiredEkuNotFoundContext(_)
        | E::EmptyEkuExtension
        | E::IssuerNotCrlSigner => CertError::Constraint,
        E::MaximumPathDepthExceeded
        | E::MaximumPathBuildCallsExceeded
        | E::MaximumSignatureChecksExceeded => CertError::ChainTooLong,
        E::UnsupportedSignatureAlgorithmContext(_)
        | E::UnsupportedSignatureAlgorithmForPublicKeyContext(_) => CertError::Unsupported,
        E::BadDer
        | E::BadDerTime
        | E::TrailingData(_)
        | E::MalformedExtensions
        | E::ExtensionValueInvalid
        | E::InvalidCertValidity
        | E::InvalidSerialNumber
        | E::UnsupportedCertVersion
        | E::SignatureAlgorithmMismatch
        | E::MalformedDnsIdentifier => CertError::BadEncoding,
        _ => CertError::Other,
    }
}

/// Validate the server's `chain` (leaf first, as sent) for `host` at `now`
/// (Unix seconds; `None` means the clock is not plausible and the check is
/// refused rather than guessed).
///
/// Checks, in order: size limits, the clock, then chain building to the
/// embedded store (signatures, validity, CA constraints, key usage and
/// `serverAuth` EKU), then the host name against the leaf's SAN.
pub fn verify_chain(
    chain: &[&[u8]],
    host: &str,
    now: Option<u64>,
    store: &TrustStore,
) -> Result<Verified, CertError> {
    if chain.is_empty() {
        return Err(CertError::BadEncoding);
    }
    if chain.len() > x509::MAX_CHAIN_LEN {
        return Err(CertError::ChainTooLong);
    }
    if chain
        .iter()
        .any(|c| c.is_empty() || c.len() > x509::MAX_CERT_LEN)
    {
        return Err(CertError::TooLarge);
    }
    let now = now.ok_or(CertError::ClockUnset)?;
    let time = UnixTime::since_unix_epoch(Duration::from_secs(now));
    let leaf_der = CertificateDer::from_slice(chain[0]);
    let ee = webpki::EndEntityCert::try_from(&leaf_der).map_err(|e| map_error(e, chain[0]))?;
    let inters: Vec<CertificateDer<'_>> = chain[1..]
        .iter()
        .map(|c| CertificateDer::from_slice(c))
        .collect();
    let anchors = store.anchors();
    let path = ee
        .verify_for_usage(
            &CHAIN_ALGS,
            &anchors,
            &inters,
            time,
            webpki::KeyUsage::server_auth(),
            None,
            None,
        )
        .map_err(|e| map_error(e, chain[0]))?;
    // A trailing dot names the same host to DNS but is not what a certificate
    // lists; refuse it instead of letting a lenient matcher decide.
    if host.ends_with('.') {
        return Err(CertError::NameMismatch);
    }
    let name = ServerName::try_from(host).map_err(|_| CertError::NameMismatch)?;
    ee.verify_is_valid_for_subject_name(&name)
        .map_err(|e| map_error(e, chain[0]))?;
    let subject = path.anchor().subject.as_ref();
    let root = (0..store.len()).find(|&i| {
        store
            .der(i)
            .and_then(|d| x509::parse(d).ok())
            .is_some_and(|c| c.subject == subject)
    });
    Ok(Verified {
        chain_len: chain.len(),
        root,
    })
}

/// The byte string a TLS 1.3 server signs in `CertificateVerify`
/// (RFC 8446 4.4.3): 64 spaces, the context string, a zero byte and the
/// transcript hash.
pub fn tls13_server_verify_message(transcript_hash: &[u8]) -> Vec<u8> {
    let mut m = Vec::with_capacity(64 + 34 + transcript_hash.len());
    m.extend_from_slice(&[0x20; 64]);
    m.extend_from_slice(b"TLS 1.3, server CertificateVerify\0");
    m.extend_from_slice(transcript_hash);
    m
}

/// Check the server's `CertificateVerify` signature with the leaf's key.
/// `scheme` is the TLS `SignatureScheme` code point; `message` comes from
/// [`tls13_server_verify_message`].
pub fn verify_handshake_signature(
    leaf: &[u8],
    scheme: u16,
    message: &[u8],
    signature: &[u8],
) -> Result<(), CertError> {
    let alg = handshake_alg(scheme).ok_or(CertError::Unsupported)?;
    let leaf_der = CertificateDer::from_slice(leaf);
    let ee = webpki::EndEntityCert::try_from(&leaf_der).map_err(|e| map_error(e, leaf))?;
    ee.verify_signature(alg, message, signature)
        .map_err(|e| match e {
            webpki::Error::UnsupportedSignatureAlgorithmForPublicKeyContext(_) => {
                CertError::Unsupported
            }
            _ => CertError::BadSignature,
        })
}

#[cfg(test)]
mod testcerts;
#[cfg(test)]
mod tests;
