#!/usr/bin/env bash
# Regenerate the browser's embedded trust store from the host's Mozilla bundle.
#
#   tools/gen-trust-store.sh [CA_DIR]
#
# Reads tools/trust-store.list (Mozilla bundle file names, in order), converts each
# root to DER and writes
#   osjeff_core/data/trust-store.bin     "OJTS1\0", u16 count, then (u16 len, DER)*
#   osjeff_core/data/trust-store.sha256  "<sha256 of the DER>  <name>" per root
# The manifest is compiled into the core and a unit test checks that every root in
# the blob hashes to the line documented here, so a silent change of the data
# cannot pass the tests. Output is deterministic: same inputs, same bytes.
#
# DEVELOPMENT ONLY: EXTRA_PEM="a.pem b.pem" appends those roots (marked "(EXTRA)" in the
# manifest). It exists to prove the verifier against a TLS-intercepting network (a
# sandbox whose gateway re-signs every site): never commit a store made with it.
#
# CA_DIR defaults to /usr/share/ca-certificates/mozilla (Debian/Ubuntu package
# `ca-certificates`); the version used is recorded in the manifest header.
set -euo pipefail
cd "$(dirname "$0")/.."
ca_dir=${1:-/usr/share/ca-certificates/mozilla}
list=tools/trust-store.list
out_bin=osjeff_core/data/trust-store.bin
out_sum=osjeff_core/data/trust-store.sha256
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

ver=$(dpkg-query -W -f='${Version}' ca-certificates 2>/dev/null || echo unknown)
: > "$tmp/sums"
n=0
while IFS= read -r name; do
  case "$name" in ''|'#'*) continue ;; esac
  src="$ca_dir/$name"
  [ -f "$src" ] || { echo "missing root: $src" >&2; exit 1; }
  openssl x509 -in "$src" -outform DER -out "$tmp/$n.der"
  sum=$(sha256sum "$tmp/$n.der" | cut -d' ' -f1)
  # Display name: the certificate subject CN (or O), not the file name.
  subj=$(openssl x509 -in "$src" -noout -subject -nameopt multiline,utf8)
  cn=$(printf '%s\n' "$subj" | sed -n 's/^ *commonName *= //p' | head -1)
  [ -n "$cn" ] || cn=$(printf '%s\n' "$subj" | sed -n 's/^ *organizationName *= //p' | head -1)
  printf '%s  %s\n' "$sum" "$cn" >> "$tmp/sums"
  n=$((n + 1))
done < "$list"

for extra in ${EXTRA_PEM:-}; do
  openssl x509 -in "$extra" -outform DER -out "$tmp/$n.der"
  sum=$(sha256sum "$tmp/$n.der" | cut -d' ' -f1)
  cn=$(openssl x509 -in "$extra" -noout -subject -nameopt multiline,utf8 | sed -n 's/^ *commonName *= //p' | head -1)
  printf '%s  %s (EXTRA)\n' "$sum" "$cn" >> "$tmp/sums"
  n=$((n + 1))
done

python3 -I - "$tmp" "$n" "$out_bin" <<'PY'
import struct, sys
tmp, n, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]
blob = b"OJTS1\0" + struct.pack(">H", n)
for i in range(n):
    der = open(f"{tmp}/{i}.der", "rb").read()
    assert len(der) < 0x10000
    blob += struct.pack(">H", len(der)) + der
open(out, "wb").write(blob)
PY

{
  echo "# SHA-256 of each embedded root (DER) and its subject name, in blob order."
  echo "# Generated by tools/gen-trust-store.sh from ca-certificates $ver (Mozilla bundle)."
  cat "$tmp/sums"
} > "$out_sum"
echo "wrote $out_bin ($(stat -c%s "$out_bin") bytes, $n roots) and $out_sum"
