//! OSJeff logo, embedded as raw RGBA (generated by tools/gen-icons.py from
//! assets/osjeff-icon.png). The kernel has no PNG decoder, so the image ships
//! pre-converted and is alpha-blitted via `Canvas::draw_rgba`.

/// 128x128 RGBA, used on the boot splash.
pub const ICON_128: &[u8] = include_bytes!("../../assets/osjeff-icon-128.raw");
pub const SIZE_128: usize = 128;

/// 40x40 RGBA, used in the dock.
pub const ICON_40: &[u8] = include_bytes!("../../assets/osjeff-icon-40.raw");
pub const SIZE_40: usize = 40;
